name: Verify Build
on:
  push:
   branches:
        - asciidoc
jobs:
    Build:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3
            
            # Set the short SHA for use in artifact names
            - name: Set short SHA
              run: echo "SHORT_SHA=$(echo ${GITHUB_SHA::7})" >> $GITHUB_ENV
      
            # Get the current date
            - name: Get current date
              run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
            
            # Pull the latest RISC-V Docs container image
            - name: Pull Container
              id: pull_container_image
              run: |
                docker pull riscvintl/riscv-docs-base-container-image:latest

            # Build PDF file using the container
            - name: Build Files
              id: build_files
              if: steps.pull_container_image.outcome == 'success'
              run: |
                docker run --rm -v ${{ github.workspace }}:/build riscvintl/riscv-docs-base-container-image:latest \
                /bin/sh -c  make debug
