name: Verify Build
on:
  push:
   branches:
        - asciidoc
jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: sudo apt-get update
            
            # Pull the latest RISC-V Docs container image
            - name: Pull Container
            - id: pull_container_image
            - run: |
                docker pull riscvintl/riscv-docs-base-container-image:latest

            # Build PDF and HTML files using the container
            - name: Build Files
            - id: build_files
            - if: steps.pull_container_image.outcome == 'success'
            - run: |
                docker run --rm -v ${{ github.workspace }}:/build riscvintl/riscv-docs-base-container-image:latest \
                /bin/sh -c 'cd ./build && make'
